#! /bin/bash

if [[ $(cat /sys/class/power_supply/BAT0/status ) == 'Charging' ]]; then 
  echo -n '^'
  cat /sys/class/power_supply/BAT0/capacity
elif [[ $(cat /sys/class/power_supply/BAT0/status ) == 'Full' ]]; then 
  echo "Full"
else 
  echo -n 'V ' 
  cat /sys/class/power_supply/BAT0/capacity
fi 

